# Generated by Django 5.2.3 on 2025-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("Employee", "Employee"), ("Manager", "Manager")],
                default="Employee",
                max_length=50,
            ),
        ),
    ]
