# Generated by Django 5.2.3 on 2025-06-24 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("requisitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="requisition",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="Additional information about the requisition",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="requisition",
            name="priority",
            field=models.CharField(
                choices=[("LOW", "LOW"), ("MEDIUM", "MEDIUM"), ("HIGH", "HIGH")],
                default="MEDIUM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="requisitionitem",
            name="unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Price at time of requisition",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="comments",
            field=models.TextField(
                blank=True, help_text="Approver comments or feedback"
            ),
        ),
        migrations.AlterField(
            model_name="approval",
            name="decision",
            field=models.CharField(
                choices=[("APPROVE", "Approve"), ("REJECT", "Reject")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="requester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requisitions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="requisition",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("APPROVED", "APPROVED"),
                    ("REJECTED", "REJECTED"),
                    ("FULFILLED", "FULFILLED"),
                    ("CANCELLED", "CANCELLED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
